version: "3.7"

services:
  api:
    build: ./kayakinsights.api/kayakinsights.api
    environment:
      MongoDB_Host: mongo
    depends_on:
      - mongo
    links:
      - mongo
    ports:
      - 5011:80

  mongo:
    image: mongo
    restart: always
    volumes:
      - ${WEBAPP_STORAGE_HOME}./si:/data/db/mongo
    ports:
      - "27017:27017"

  spa:
    build: ./kayakinsightspa
    depends_on:
      - api
    ports:
      - 80:80

  #  mongo-express:
  #    image: mongo-express
  #    restart: always
  #    ports:
  #      - 8081:8081
  #    environment:
  #      ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #      ME_CONFIG_MONGODB_ADMINPASSWORD: example
  #    depends_on:
  #      - mongo

  ngrok:
    image: shkoliar/ngrok:latest
    ports:
      - 4551:4551
    links:
      - api
      - spa
    environment:
      - DOMAIN=spa
      - PORT=80
